name: "publish-core-lib"
run-name: "Deploys ll1-generator-core to npm"
on:
  push:
    branches:
      - "main"
    paths:
      - "core/**"
jobs:
  run:
    name: "Run tests and deploy to npm"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "cd into core/"
        run: cd core
      - name: "Install Node"
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18.x
      - name: "Install dependencies"
        run: npm install
      - name: "Run unit tests"
        run: npm test
